### ISSUE TITLE
無法使用材料數據

### ISSUE THREAD

**Issue by siderlivier** [Tualin14/ArisStudio#3]
[https://oss.dza.vin/share@dzaaaaaa.com/baPlayer%E5%8F%AF%E7%94%A8%E7%B4%A0%E6%9D%90%E9%9B%86](url)
中給的四個檔案全部無法開啟，點開會跳出這個畫面
![問題回報](https://user-images.githubusercontent.com/122412348/211700006-7b73e62a-f1f2-421a-89d0-6ebe087a2346.png)
還有要求我登入Microsoft 但登入後卻告訴我出了問題
但ba撥放器本體可以正常開啟，求解決辦法

**Comment by Tualin14** [comment]
不需要登陸Microsoft
雲的那個標誌是下載

雖然不知道你用的什麼軟件解壓的
但我建議你使用 7zip(https://www.7-zip.org/) 来解压

**Comment by siderlivier** [comment]
謝謝我已經下載完了，可以正常使用了
非常感謝

**Comment by Tualin14** [comment]
好的
