### ISSUE TITLE
克隆项目构建工程时无法找到对应脚本

### ISSUE THREAD

**Issue by xiongnemo** [Tualin14/ArisStudio#4]
尝试直接从编辑器中运行时，有如下提示：
![image](https://user-images.githubusercontent.com/38759782/212227546-f47682ec-24d0-491c-9afc-bb5299d7ff23.png)
尝试构建时，有如下提示：
![image](https://user-images.githubusercontent.com/38759782/212227751-b9b98d34-b924-4830-9402-605166e81359.png)
查找原因时有看到一篇[文章](https://www.cnblogs.com/hair-duang-duang/p/16366239.html)，节选其中的两句话：

> 原因是我们的gitignore中不小心加入了*.meta（直接使用了官方的ignore文件没有注意到这个）

和

> 可以看到这个脚本实际上有一个guid，.unity文件实际上就是通过这个来找脚本的。

当前版本 [5a0e1c7](https://github.com/Tualin14/ArisStudio/commit/5a0e1c7852b737a2e89969284b7bb66459830129) 中对应的[.gitignore 文件](https://github.com/Tualin14/ArisStudio/blob/5a0e1c7852b737a2e89969284b7bb66459830129/.gitignore) 中确实忽略了 `*.meta` 文件。

这个问题应该要您通过单独克隆仓库然后打开项目来复现一次；如果您确定这个是找不到脚本的原因的话，希望可以把这些 meta 文件加入源代码树。

**Comment by Tualin14** [comment]
是的，我已经发现这个问题了，我现在在重构代码
因为目前一版一版填新功能造成越来越乱，
如果你不着急的话，可以等一下一版吗？
或者你需要添加什么，我看看能不能顺便加上。

**Comment by xiongnemo** [comment]
> 是的，我已经发现这个问题了，我现在在重构代码 因为目前一版一版填新功能造成越来越乱， 如果你不着急的话，可以等一下一版吗？ 或者你需要添加什么，我看看能不能顺便加上。

我个人想改那个选项 (Select, SelectButton) 的，因为这个跟实际体验中还是有明显的差别：
* 游戏中选择选项以后不会有延迟，而且会直接跳到下面的剧情，而不是当前实现中能观察到的选项消失后还要再点击一次；
* 感觉选择按钮的布局（上下）看起来怪怪的……

别的暂时没有了，既然是已经知晓了我就把这个 issue 关掉了~

**Comment by xiongnemo** [comment]
> 是的，我已经发现这个问题了，我目前在重构代码，因为目前一版一版填新功能造成越来越乱。
> 
> main分支附上了*.meta文件
> 
> 因为在重构代码，文件结构，程序逻辑有一定变化，所以建议等下一版的提交

同步分支以后可以构建了🆗

**Comment by Tualin14** [comment]
那个是1.3.4版加上的，之前是没有延迟
但根据反馈，大多数人录制的视频时
- 选择按钮停留时间过短
- 选择结束后立马进行接下来播放

会造成观众无法看清

另外为了从头至尾的自动播放，在1.3.4版进行了选择按钮停留的改动

如果你认为这样不合适，可以用1.3.3版

**Comment by Tualin14** [comment]
按钮位置问题
Duplicate of #6
