### ISSUE TITLE
加载新剧情脚本时部分旧元素仍然保留并影响当前剧情播放

### ISSUE THREAD

**Issue by xiongnemo** [Tualin14/ArisStudio#7]
如图所示：

![image](https://user-images.githubusercontent.com/38759782/212258946-d59db383-ebbe-42ba-b748-1192d618e401.png)

![image](https://user-images.githubusercontent.com/38759782/212259541-9c98329e-350d-47d1-b925-619f865e6779.png)

猜测是因为没有清空原有 `C_Control.cs` 中相关字典和 `targetList` 数据，导致渲染和跳转都出现问题。

**Comment by Tualin14** [comment]
对的，所以目前解决办法是出现打开或者重新运行
这是早期用setting文件打开程序直接播放的遗留问题

在下一大版修改计划中

**Comment by Tualin14** [comment]
已在新版本修复

**Comment by xiongnemo** [comment]
感谢！
